# Generated by Django 5.2 on 2026-03-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('V', 'VISA'), ('C', 'CASH'), ('T', 'TICKET RESTAURANT')], verbose_name='Payment type')),
                ('ticket_datetime', models.DateTimeField(verbose_name='Date and time ticket creation')),
                ('zeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='zeta.zeta', verbose_name='ticket')),
            ],
        ),
    ]
