# Generated by Django 5.2 on 2026-03-20 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('V', 'VISA'), ('C', 'CASH'), ('T', 'TICKET RESTAURANT')], max_length=20, verbose_name='Payment type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of order created')),
                ('status', models.CharField(choices=[('O', 'OPENED'), ('A', 'ACTIVE'), ('C', 'CLOSED')], default='O', verbose_name='order status')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended', models.BooleanField(default=False, verbose_name='products order sended')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_ordered', to='products.product')),
            ],
            options={
                'verbose_name': 'Productos ordenados dentro de una comanda',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products_in_order', through='core.ProductsInOrder', to='products.product', verbose_name='products in order'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number of table')),
                ('recommended_guests', models.PositiveIntegerField(default=2, verbose_name='Number of guests per table')),
                ('map_units', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Number of squares in establishment map')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='core.section', verbose_name='section tables')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
                'unique_together': {('number', 'section')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.table', verbose_name='orders of table'),
        ),
    ]
