# Generated by Django 5.2 on 2026-03-25 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of order created')),
                ('status', models.CharField(choices=[('O', 'OPENED'), ('A', 'ACTIVE'), ('C', 'CLOSED')], default='O', max_length=1, verbose_name='order status')),
                ('observations', models.TextField(blank=True, default=' ', verbose_name='observations')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sended', models.BooleanField(default=False, verbose_name='product order sended')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='comanda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Productos ordenados dentro de una comanda',
            },
        ),
        migrations.CreateModel(
            name='OrderItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_extras', to='products.productallowedextra', verbose_name='extra permitido')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_extras', to='core.orderitem', verbose_name='línea de comanda')),
            ],
            options={
                'verbose_name': 'Extra seleccionado en comanda',
                'verbose_name_plural': 'Extras seleccionados en comanda',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Number of table')),
                ('guests_quantity', models.PositiveIntegerField(default=2, verbose_name='Number of guests per table')),
                ('map_units', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Quantity of squares in establishment map')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='core.section', verbose_name="section's tables")),
                ('waiter', models.ForeignKey(blank=True, limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tables', to=settings.AUTH_USER_MODEL, verbose_name="waiter's tables")),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.table', verbose_name='orders of table'),
        ),
    ]
