# Generated by Django 5.2 on 2026-03-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='busy',
            field=models.BooleanField(default=False, verbose_name='Table busy'),
        ),
    ]
