# Generated by Django 5.2 on 2026-03-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_table_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemextra',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and time of order closed'),
        ),
    ]
