# Generated by Django 5.2 on 2026-04-04 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitemextra_quantity_alter_order_closed_at'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='observations',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='observations of order product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sended',
            field=models.BooleanField(default=False, verbose_name='order product sended'),
        ),
        migrations.AlterField(
            model_name='orderitemextra',
            name='allowed_extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_extras', to='products.productallowedextra', verbose_name='extra permitido'),
        ),
    ]
