# Generated by Django 5.2 on 2026-04-08 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem_observations_alter_orderitem_product_and_more'),
        ('products', '0002_alter_productallowedextra_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='products.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='orderitemextra',
            name='allowed_extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_extras', to='products.productallowedextra', verbose_name='extra permitido'),
        ),
        migrations.AlterField(
            model_name='orderitemextra',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='core.orderitem', verbose_name='línea de comanda'),
        ),
    ]
