# Generated by Django 5.2 on 2026-04-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.table', verbose_name='orders of table'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'section')},
        ),
    ]
