# Generated by Django 5.2 on 2026-04-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_table_alter_table_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sended',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('S', 'SENDED'), ('D', 'DONE'), ('DE', 'DELIVERED')], default='P', max_length=2, verbose_name='Order status'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('P', 'PENDING'), ('S', 'SENDED'), ('D', 'DONE'), ('DE', 'DELIVERED')], default='P', max_length=2, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observations'),
        ),
    ]
