# Generated by Django 5.2.12 on 2026-04-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_orderitem_sended_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
