# Generated by Django 5.2 on 2026-03-27 23:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime report created')),
                ('closed_at', models.DateTimeField(verbose_name='Datetime report closed')),
                ('total_operations', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_visa_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('V', 'VISA'), ('C', 'CASH'), ('T', 'TICKET RESTAURANT')], max_length=20, verbose_name='Payment type')),
                ('ticket_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date and time ticket creation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.order')),
                ('zeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='zeta.zeta', verbose_name='zeta')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
