# Generated by Django 5.2 on 2026-03-19 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_datetime', models.DateTimeField(verbose_name='Datetime report created')),
                ('end_datetime', models.DateTimeField(verbose_name='Datetime report closed')),
                ('total_operations', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_visa_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
