# Generated by Django 5.2 on 2026-04-04 21:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-ticket_datetime'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='zeta',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Zeta', 'verbose_name_plural': 'Zetas'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='zeta',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime report closed'),
        ),
        migrations.AlterField(
            model_name='zeta',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zeta',
            name='total_cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zeta',
            name='total_operations',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='zeta',
            name='total_visa_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
