# Generated by Django 5.2 on 2026-04-08 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderitem_product_and_more'),
        ('zeta', '0002_alter_ticket_options_alter_zeta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.order'),
        ),
    ]
