# Generated by Django 5.2 on 2026-04-09 02:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderitem_product_and_more'),
        ('zeta', '0004_operation_and_ticket_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='zeta',
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cash amount'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.order', verbose_name='Order tickets'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_summary',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='visa_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Visa amount'),
        ),
    ]
