# Generated by Django 5.2 on 2026-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('encargado', 'Encargado'), ('trabajador', 'Trabajador')], default='admin', max_length=15)),
                ('permision', models.CharField(choices=[('admin', 'Poder absoluto'), ('CRUD', 'Crear, actualizar y eliminar'), ('Observer', 'Solo observar')], default='CRUD', max_length=10)),
            ],
        ),
    ]
