from django.db import models

# NOMBRE
# PRECIO
# IMAGEN 
# SECCION (CAFETERIA, COMIDA, BEBIDA, VITRINA...)
# EXTRAS (DE PAGO (EXTRA DE QUESO, EXTRA DE BACON... ) Y DE NO PAGO (EXTRA DE AZUCAR, CON TOMATE EN EL BOCADILLO, LECHE FRÍA, HUEVO POCO HECHO...))
