# Generated by Django 5.2 on 2026-03-20 23:39

import django.core.validators
import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='precio')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Producto Nuevo', max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('image', models.ImageField(blank=True, default='products\\colacao.bmp', null=True, upload_to=products.models.get_media_products_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])], verbose_name='image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAllowedExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False, verbose_name='obligatorio')),
                ('max_quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad máxima')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_allowed_extra_links', to='products.extra', verbose_name='extra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_allowed_extra_links', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Extra permitido en producto',
                'verbose_name_plural': 'Extras permitidos en productos',
                'ordering': ['product__name', 'extra__name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allowed_extras',
            field=models.ManyToManyField(blank=True, related_name='allowed_products', through='products.ProductAllowedExtra', to='products.extra', verbose_name='extras permitidos'),
        ),
        migrations.AddConstraint(
            model_name='productallowedextra',
            constraint=models.UniqueConstraint(fields=('product', 'extra'), name='unique_product_allowed_extra'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
    ]
