# Generated by Django 5.2 on 2026-04-08 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productallowedextra',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allowed_in_products', to='products.extra', verbose_name='extra'),
        ),
        migrations.AlterField(
            model_name='productallowedextra',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_extra_links', to='products.product', verbose_name='producto'),
        ),
    ]
