# Generated by Django 5.2 on 2026-04-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productallowedextra_extra_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category', 'price')},
        ),
        migrations.AddField(
            model_name='product',
            name='kitchen',
            field=models.BooleanField(default=False, verbose_name='Kitchen product'),
        ),
    ]
